build(devcontainer): :arrow_up: update devcontainer

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -13,6 +13,9 @@ COPY --from=docker.io/golang:1.26.1-alpine-3.23@sha256:f85330846cde1e57ca9ec3093
 # Install additional packages
 RUN apk update && apk add sudo openssh curl git bash fish micro graphviz nodejs npm mosquitto-clients dbus dbus-x11 starship
 
+# Install starship
+RUN cd /tmp && curl -sS https://starship.rs/install.sh | sh -s -- -y || exit -1
+
 # Add non-root user
 ARG USER_NAME=vscode
 ARG USER_UID=1000
@@ -30,10 +33,22 @@ RUN mkdir -p $XDG_RUNTIME_DIR && chmod 0700 $XDG_RUNTIME_DIR && chown $USER_UID:
 
 USER $USER_NAME
 
-# The base container sets XDG_CACHE_HOME XDG_CONFIG_HOME specifically for the root user, we can't unset them in a way that vscode will pick up, so we set them to values for the new user.
-# Installing go extensions via vscode use these paths so if we just leave it set to /root/.cache we'll get permission errors.
+ENV _CONTAINERS_USERNS_CONFIGURED=""
+
+# The base container sets XDG_CACHE_HOME XDG_CONFIG_HOME specifically for the root user, we can't unset them in a way
+# that vscode will pick up, so we set them to values for the new user. Installing go extensions via vscode use these
+# paths so if we just leave it set to /root/.cache we'll get permission errors.
 ENV XDG_CONFIG_HOME=/home/$USER_NAME/.config
 ENV XDG_CACHE_HOME=/home/$USER_NAME/.cache
-RUN mkdir -p $XDG_CONFIG_HOME $XDG_CACHE_HOME
+# Set up XDG_RUNTIME_DIR
+RUN export XDG_RUNTIME_DIR=/tmp/$USER_UID-runtime-dir \
+    && mkdir $XDG_RUNTIME_DIR \
+    && chmod 0700 $XDG_RUNTIME_DIR
+ENV XDG_RUNTIME_DIR=/tmp/$USER_UID-runtime-dir
+
+# Set up shell(s).
+RUN mkdir -p ~/.config/fish \
+    && echo "starship init fish | source" >>~/.config/fish/config.fish \
+    && echo 'eval "$(starship init bash)"' >>~/.bashrc
 
 ENTRYPOINT ["/usr/bin/fish"]
